const { loginEvent, updateUserEvent, createProductEvent, listProductEvent, oneProductEvent, updateProductEvent, deleteProductEvent, listArchivesEvent, createLeadEvent, listLeadEvent, deleteLeadEvent, updateLeadEvent, createCompanyEvent, listCompanyEvent, oneCompanyEvent, updateCompanyEvent, deleteCompanyEvent, oneLeadEvent, createWorkerEvent, listWorkerEvent, oneWorkerEvent, updateWorkerEvent, deleteWorkerEvent, createCategoryEvent, listCategoryEvent, oneCategoryEvent, updateCategoryEvent, deleteCategoryEvent, createInvalidEvent, listInvalidEvent, homeEvent } = require("@/universal/eventNames")
const { createProduct, listProduct, oneProduct, updateProduct, deleteProduct, listArchives, home } = require("./controller/product")
const { login, updateUser } = require("./controller/login")
const { createLead, listLead, oneLead, deleteLead, updateLead } = require("./controller/lead")
const { createCompany, listCompany, oneCompany, updateCompany, deleteCompany } = require("./controller/company")
const { createWorker, listWorker, oneWorker, updateWorker, deleteWorker } = require("./controller/worker")
const { createCategory, listCategory, oneCategory, updateCategory, deleteCategory } = require("./controller/category")
const { createInvalid, listInvalids } = require("./controller/invalid")

module.exports.eventController = async (ipcMain) => {
    try {
        ipcMain.handle(loginEvent, login())
        ipcMain.handle(updateUserEvent, updateUser())
        ipcMain.handle(createProductEvent, createProduct())
        ipcMain.handle(listProductEvent, listProduct())
        ipcMain.handle(oneProductEvent, oneProduct())
        ipcMain.handle(updateProductEvent, updateProduct())
        ipcMain.handle(deleteProductEvent, deleteProduct())
        ipcMain.handle(listArchivesEvent, listArchives())
        ipcMain.handle(createLeadEvent, createLead())
        ipcMain.handle(listLeadEvent, listLead())
        ipcMain.handle(oneLeadEvent, oneLead())
        ipcMain.handle(updateLeadEvent, updateLead())
        ipcMain.handle(deleteLeadEvent, deleteLead())
        ipcMain.handle(createCompanyEvent, createCompany())
        ipcMain.handle(listCompanyEvent, listCompany())
        ipcMain.handle(oneCompanyEvent, oneCompany())
        ipcMain.handle(updateCompanyEvent, updateCompany())
        ipcMain.handle(deleteCompanyEvent, deleteCompany())
        ipcMain.handle(createWorkerEvent, createWorker())
        ipcMain.handle(listWorkerEvent, listWorker())
        ipcMain.handle(oneWorkerEvent, oneWorker())
        ipcMain.handle(updateWorkerEvent, updateWorker())
        ipcMain.handle(deleteWorkerEvent, deleteWorker())
        ipcMain.handle(createCategoryEvent, createCategory())
        ipcMain.handle(listCategoryEvent, listCategory())
        ipcMain.handle(oneCategoryEvent, oneCategory())
        ipcMain.handle(updateCategoryEvent, updateCategory())
        ipcMain.handle(deleteCategoryEvent, deleteCategory())
        ipcMain.handle(createInvalidEvent, createInvalid())
        ipcMain.handle(listInvalidEvent, listInvalids())
        ipcMain.handle(homeEvent, home())
    } catch (error) {
        console.log(error)
        console.log('Asosiy controller ichida hatolik')
    }
}
